INSERT INTO accounts (code, name, type) VALUES
  ('3100','Kontingent','Inntekt'),
  ('3200','Vikentokt-avgifter','Inntekt'),
  ('3210','Landsleir-avgifter','Inntekt'),
  ('3220','Juletur-avgifter','Inntekt'),
  ('3230','Nabbentur-avgifter','Inntekt'),
  ('3300','Offentlige tilskudd','Inntekt'),
  ('3310','Kommunale tilskudd','Inntekt'),
  ('3320','Frifond','Inntekt'),
  ('3330','Utbytte Gjensidige','Inntekt'),
  ('3340','Støtte krets/forbund','Inntekt'),
  ('3350','Sponsormidler','Inntekt'),
  ('3400','Loddsalg/arrangementer','Inntekt'),
  ('3410','Salg utstyr','Inntekt'),
  ('3420','Salg mat/drikke','Inntekt'),
  ('3500','Grasrotandelen','Inntekt'),
  ('3510','Spond','Inntekt'),
  ('3600','Renteinntekter','Inntekt'),
  ('3900','Vipps-utbetaling til bank','Inntekt'),
  ('4100','Aktivitetsutgifter','Utgift'),
  ('4110','Årsleir-utgifter','Utgift'),
  ('4120','Juletur-utgifter','Utgift'),
  ('4130','Nabbentur-utgifter','Utgift'),
  ('4140','Andre turutgifter','Utgift'),
  ('4200','Kahytten/lokale','Utgift'),
  ('4210','Strøm','Utgift'),
  ('4220','Kommunale avgifter','Utgift'),
  ('4300','Forsikring','Utgift'),
  ('4400','Kretskontingent','Utgift'),
  ('4410','Longship-andel','Utgift'),
  ('4420','Follo Krets','Utgift'),
  ('4500','Diverse utgifter','Utgift'),
  ('4510','Tropp/gruppeutstyr','Utgift'),
  ('4600','Porto/kontorrekvisita','Utgift'),
  ('4700','Bankgebyrer','Utgift'),
  ('4800','Utdanningsetaten','Utgift'),
  ('4900','Andre utgifter','Utgift'),
  ('5100','Båtvedlikehold','Utgift'),
  ('5110','Drivstoff båt','Utgift'),
  ('5120','Båtutstyr','Utgift'),
  ('5130','Seil/rigg','Utgift'),
  ('5140','Motor/mekanisk','Utgift'),
  ('5150','Opplag','Utgift'),
  ('5160','Havneleie','Utgift'),
  ('5170','Sjøforsikring','Utgift'),
  ('5190','Andre båtkostnader','Utgift')
ON CONFLICT (code) DO NOTHING;

INSERT INTO rules (source_type, match_field, match_text, account_code, description, priority) VALUES
  ('bank_income','pay_type','RENTER','3600','Renteinntekter',10),
  ('bank_income','combined','NORSK TIPPING','3500','Grasrotandel',10),
  ('bank_income','combined','SPOND','3510','Spond',10),
  ('bank_income','combined','GJENSIDIGESTIFTELSEN','3330','Utbytte Gjensidige forsikring',10),
  ('bank_income','combined','VIPPS','3900','Vipps-utbetaling til bank',10),
  ('bank_income','combined','OSLOSPEIDERNE','3340','Tilskudd Oslospeiderne',10),
  ('bank_income','combined','NORGES SPEIDERFORBUND','3340','Norges Speiderforbund',10),
  ('bank_expense','combined','GJENSIDIGE FORSIKRING','4300','Forsikring Gjensidige',10),
  ('bank_expense','combined','FORTUM','4210','Strøm Fortum',10),
  ('bank_expense','combined','BÆRUM KOMMUNE','4220','Kommunale avgifter',10),
  ('bank_expense','combined','BAERUM','4220','Kommunale avgifter',10),
  ('bank_expense','combined','SOLVIK','5150','Opplag Solvik',10),
  ('bank_expense','combined','SOLLERUD','5160','Havneleie Sollerud',10),
  ('bank_expense','combined','LONGSHIP','4110','Landsleir-utgift (Longship)',10),
  ('bank_expense','combined','FOLLO KRETS','4420','Follo Krets',10),
  ('bank_expense','combined','OSLOSPEIDERNE','4400','Kretskontingent',10),
  ('bank_expense','combined','NORGES SPEIDERFORBUND','4400','Forbundskontingent',10),
  ('bank_expense','combined','UTDANNINGSETATEN','4800','Utdanningsetaten',10),
  ('bank_expense','combined','LØVENSKIOLD','4200','Kahytten (Løvenskiold)',10),
  ('bank_expense','pay_type','OMKOSTNINGER','4700','Bankgebyrer',10),
  ('vipps','combined','LODD','3400','Loddsalg',10),
  ('vipps','combined','ÅRSFEST','3400','Loddsalg',10),
  ('vipps','combined','VIKEN','3200','Vikentokt-avgift',10),
  ('vipps','combined','NABBEN','3230','Nabbentur',10),
  ('vipps','combined','OVERSKUDD','3230','Nabbentur',10),
  ('vipps','combined','DRIVSTOFF','3200','Drivstoff seiltur',10),
  ('vipps','combined','JULE','3220','Juletur-avgift',10),
  ('vipps','combined','BENTO','3220','Juletur-avgift',10)
ON CONFLICT DO NOTHING;
