INSERT INTO accounts (code, name, type) VALUES
  ('3100','Kontingent','Inntekt'),
  ('3200','Vikentokt/turavgifter','Inntekt'),
  ('3210','Landsleir-avgifter','Inntekt'),
  ('3220','Juletur-avgifter','Inntekt'),
  ('3230','Nabbentur-avgifter','Inntekt'),
  ('3300','Frifond','Inntekt'),
  ('3310','Kommunalt tilskudd','Inntekt'),
  ('3320','Momskompensasjon','Inntekt'),
  ('3330','Utbytte Gjensidige','Inntekt'),
  ('3340','Speiderforbund-støtte','Inntekt'),
  ('3350','Andre tilskudd/støtte','Inntekt'),
  ('3400','Lotteri/loddsalg','Inntekt'),
  ('3410','Vaffelsalg/matsalg','Inntekt'),
  ('3420','Kalendersalg','Inntekt'),
  ('3500','Norsk Tipping (Grasrot)','Inntekt'),
  ('3510','Spond-inntekter','Inntekt'),
  ('3600','Renteinntekter','Inntekt'),
  ('3900','Andre inntekter','Inntekt'),
  ('4100','Vikentokt-utgifter','Utgift'),
  ('4110','Årsleir-utgifter','Utgift'),
  ('4120','Juletur-utgifter','Utgift'),
  ('4130','Nabbentur-utgifter','Utgift'),
  ('4140','Andre turer/aktiviteter','Utgift'),
  ('4200','Kahytten (lokale)','Utgift'),
  ('4210','Strøm (Fortum)','Utgift'),
  ('4220','Kommunale avgifter','Utgift'),
  ('4300','Forsikring (Gjensidige)','Utgift'),
  ('4400','Kontingent krets/forbund','Utgift'),
  ('4410','Longship-andel','Utgift'),
  ('4420','Follo Krets','Utgift'),
  ('4500','Troppens utgifter','Utgift'),
  ('4510','Gruppens utgifter','Utgift'),
  ('4600','Kurs og opplæring','Utgift'),
  ('4700','Bankgebyrer','Utgift'),
  ('4800','Utdanningsetaten','Utgift'),
  ('4900','Andre utgifter','Utgift'),
  ('5100','Båtvedlikehold/rep.','Utgift'),
  ('5110','Bento vedlikehold','Utgift'),
  ('5120','Seil, rigg og utstyr','Utgift'),
  ('5130','Motor og drivstoff','Utgift'),
  ('5140','Sikkerhetsutstyr','Utgift'),
  ('5150','Opplag/kraning','Utgift'),
  ('5160','Havneleie','Utgift'),
  ('5170','Båtforsikring','Utgift'),
  ('5190','Andre båtkostnader','Utgift')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO rules (source_type, match_field, match_text, account_code, description, priority) VALUES
  ('bank_income','pay_type','RENTER','3600','Renteinntekter',10),
  ('bank_income','combined','NORSK TIPPING','3500','Grasrotandel',10),
  ('bank_income','combined','SPOND','3510','Spond',10),
  ('bank_income','combined','GJENSIDIGESTIFTELSEN','3330','Utbytte Gjensidige forsikring',10),
  ('bank_income','combined','VIPPS','3900','Vipps-utbetaling til bank',10),
  ('bank_income','combined','OSLOSPEIDERNE','3340','Tilskudd Oslospeiderne',10),
  ('bank_income','combined','NORGES SPEIDERFORBUND','3340','Norges Speiderforbund',10),
  ('bank_expense','combined','GJENSIDIGE FORSIKRING','4300','Forsikring Gjensidige',10),
  ('bank_expense','combined','FORTUM','4210','Strøm Fortum',10),
  ('bank_expense','combined','BÆRUM KOMMUNE','4220','Kommunale avgifter',10),
  ('bank_expense','combined','BAERUM','4220','Kommunale avgifter',10),
  ('bank_expense','combined','SOLVIK','5150','Opplag Solvik',10),
  ('bank_expense','combined','SOLLERUD','5160','Havneleie Sollerud',10),
  ('bank_expense','combined','LONGSHIP','4110','Landsleir-utgift (Longship)',10),
  ('bank_expense','combined','FOLLO KRETS','4420','Follo Krets',10),
  ('bank_expense','combined','OSLOSPEIDERNE','4400','Kretskontingent',10),
  ('bank_expense','combined','NORGES SPEIDERFORBUND','4400','Forbundskontingent',10),
  ('bank_expense','combined','UTDANNINGSETATEN','4800','Utdanningsetaten',10),
  ('bank_expense','combined','LØVENSKIOLD','4200','Kahytten (Løvenskiold)',10),
  ('bank_expense','pay_type','OMKOSTNINGER','4700','Bankgebyrer',10),
  ('vipps','combined','LODD','3400','Loddsalg',10),
  ('vipps','combined','ÅRSFEST','3400','Loddsalg',10),
  ('vipps','combined','VIKEN','3200','Vikentokt-avgift',10),
  ('vipps','combined','NABBEN','3230','Nabbentur',10),
  ('vipps','combined','OVERSKUDD','3230','Nabbentur',10),
  ('vipps','combined','DRIVSTOFF','3200','Drivstoff seiltur',10),
  ('vipps','combined','JULE','3220','Juletur-avgift',10),
  ('vipps','combined','BENTO','3220','Juletur-avgift',10)
ON CONFLICT DO NOTHING;
